version: '3.8'

services:
  app:
    image: data-collector-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/datacollector
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - data-collector-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: datacollector
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - data-collector-network

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - data-collector-network

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - data-collector-network

networks:
  data-collector-network:
    driver: bridge

volumes:
  db_data: